### ISSUE TITLE
automation sdk中没有封装的API如何调用 ？

### ISSUE THREAD

**Issue by AbstractWorld** [NOWYOU/vSphere-Python-Automation-Scripts#2]
我在CSDN上看到了您的文章，又去看了下vSphere提供的开发者工具包，在实际测试的时候发现了一些问题：
Pyvmomi和vSphere automation sdk都只封装了一些接口，对于没有封装的SOAP API和REST API如何直接调用？
希望能解答一下，谢谢。

**Comment by NOWYOU** [comment]
SDK就是REST API，Pyvmomi本质上调用的是MOB。你可以使用PowerCLI调用SOAP API。

**Comment by undolog** [comment]
懂了，谢谢
